#!/usr/bin/env bash
set -euo pipefail

function exe() {
    echo "$(pwd)\$"
    echo "$@"
    "$@"
}

COMMIT=$(git rev-parse --verify HEAD 2>/dev/null)

git clean -xdf
git reset --hard ${COMMIT}

PM=$(basename $1)
VSN_PM=$(${PM} --version)
PKG_NAME="$(node -e "var pkg = require('./package.json'); console.log(pkg.name);")"
TIMESTAMP=$(date +%s%N)

PACKAGE_JSON_SCRIPTS_DIR="/tmp/package-json-scripts/${PM}-${VSN_PM}"

CMD=$(echo "$@" | sed 's/[^a-zA-Z0-9]/_/g')
DIR="${PACKAGE_JSON_SCRIPTS_DIR}/${TIMESTAMP}.${CMD}.${PKG_NAME}"
exe rm -rf "${DIR}"
mkdir -p "${DIR}"
PACKAGE_JSON_SCRIPTS_DIR="${DIR}" exe "$@"
exe tree "${DIR}"

git add -f .
git commit -m "${CMD}"
